const images =[ 
    'https://images.unsplash.com/photo-1637819203905-2294a31391d3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1647021038407-fca3bfd3bf0e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1644833384541-b273dbb40caa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1651559111403-3a0ecfb93c09?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1645929148848-b4ad7c145585?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1646773777979-8242c6ee91c7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1648348329481-93f85519a868?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1648649459257-f8fb0bce6ec9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
    'https://images.unsplash.com/photo-1649984302689-19617ea0620e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&h=1050&q=80',
]
exports.data = [
  {
    id: 1,
    title: "🔥 24h Training",
    content: [
      {
        id: 1,
        img: images[0],
        title: "Gold Hand #91",
        username: "@freezecorle...",
        account: "0x890aac...",

      },
      {
        id: 2,
        img: images[1],
        title: "Cyber Robo #2663",
        username: "@0x2bc08c...",
        account: "0x2bc08c...",
      },
      {
        id: 3,
        img: images[2],
        title: "Cyber Wild Man #745",
        username: "@0x4eh0t4...",
        account: "0x4eh0t4...",
      },
      {
        id: 4,
        img: images[3],
        title: "Old Gold #874",
        username: "@0x3cr4c8...",
        account: "0x3cr4c8...",
      },
      {
        id: 5,
        img: images[4],
        title: "Meraki Cyber #523",
        username: "@val2o543...",
        account: "0xh36f9n...",
      },
      {
        id: 6,
        img: images[5],
        title: "Cyber Robo #14",
        username: "@0xb0gfadr...",
        account: "0xb0gfadr...",
      },
      {
        id: 7,
        img: images[6],
        title: "Meraki Cyber #1463",
        username: "@0x4de6fr...",
        account: "0x4de6fr...",
      },
      {
        id: 8,
        img: images[7],
        title: "Spidey Cyber #874",
        username: "@spideycyber...",
        account: "@0xl9ka7c...",
      },
      {
        id: 9,
        img: images[8],
        title: "Cyber Wild Girls #44",
        username: "@0xg4l0fad...",
        account: "@0xg4l0fa...",
      },
    ],
  },
  {
    id: 2,
    title: "🆕 Latest Shows",
    content:  [
        {
            id: 4,
            img: images[3],
            title: "Old Gold #874",
            username: "@0x3cr4c8...",
            account: "0x3cr4c8...",
          },
          {
            id: 5,
            img: images[4],
            title: "Meraki Cyber #523",
            username: "@val2o543...",
            account: "0xh36f9n...",
          },
          {
            id: 6,
            img: images[5],
            title: "Cyber Robo #14",
            username: "@0xb0gfadr...",
            account: "0xb0gfadr...",
          },
        {
          id: 1,
          img: images[0],
          title: "Gold Hand #91",
          username: "@freezecorle...",
          account: "0x890aac...",
  
        },
        {
          id: 2,
          img: images[1],
          title: "Cyber Robo #2663",
          username: "@0x2bc08c...",
          account: "0x2bc08c...",
        },
        {
          id: 3,
          img: images[2],
          title: "Cyber Wild Man #745",
          username: "@0x4eh0t4...",
          account: "0x4eh0t4...",
        },
        
        {
          id: 7,
          img: images[6],
          title: "Meraki Cyber #1463",
          username: "@0x4de6fr...",
          account: "0x4de6fr...",
        },
        {
          id: 8,
          img: images[7],
          title: "Spidey Cyber #874",
          username: "@spideycyber...",
          account: "@0xl9ka7c...",
        },
        {
          id: 9,
          img: images[8],
          title: "Cyber Wild Girls #44",
          username: "@0xg4l0fad...",
          account: "@0xg4l0fa...",
        },
      ],
  },
  {
    id: 3,
    title: "📈 Most Popular",
    content:  [
        {
            id: 7,
            img: images[6],
            title: "Meraki Cyber #1463",
            username: "@0x4de6fr...",
            account: "0x4de6fr...",
          },
          {
            id: 8,
            img: images[7],
            title: "Spidey Cyber #874",
            username: "@spideycyber...",
            account: "@0xl9ka7c...",
          },
          {
            id: 9,
            img: images[8],
            title: "Cyber Wild Girls #44",
            username: "@0xg4l0fad...",
            account: "@0xg4l0fa...",
          },
        {
          id: 1,
          img: images[0],
          title: "Gold Hand #91",
          username: "@freezecorle...",
          account: "0x890aac...",
  
        },
        {
          id: 2,
          img: images[1],
          title: "Cyber Robo #2663",
          username: "@0x2bc08c...",
          account: "0x2bc08c...",
        },
        {
          id: 3,
          img: images[2],
          title: "Cyber Wild Man #745",
          username: "@0x4eh0t4...",
          account: "0x4eh0t4...",
        },
        {
          id: 4,
          img: images[3],
          title: "Old Gold #874",
          username: "@0x3cr4c8...",
          account: "0x3cr4c8...",
        },
        {
          id: 5,
          img: images[4],
          title: "Meraki Cyber #523",
          username: "@val2o543...",
          account: "0xh36f9n...",
        },
        {
          id: 6,
          img: images[5],
          title: "Cyber Robo #14",
          username: "@0xb0gfadr...",
          account: "0xb0gfadr...",
        },
        
      ],
  },
  {
    id: 4,
    title: "💎 In Genesis",
    content:  [

       
          {
            id: 2,
            img: images[1],
            title: "Cyber Robo #2663",
            username: "@0x2bc08c...",
            account: "0x2bc08c...",
          },
        {
          id: 5,
          img: images[4],
          title: "Meraki Cyber #523",
          username: "@val2o543...",
          account: "0xh36f9n...",
        },
        {
          id: 6,
          img: images[5],
          title: "Cyber Robo #14",
          username: "@0xb0gfadr...",
          account: "0xb0gfadr...",
        },
        {
            id: 3,
            img: images[2],
            title: "Cyber Wild Man #745",
            username: "@0x4eh0t4...",
            account: "0x4eh0t4...",
          },
          {
            id: 7,
            img: images[6],
            title: "Meraki Cyber #1463",
            username: "@0x4de6fr...",
            account: "0x4de6fr...",
          },
        
          {
            id: 1,
            img: images[0],
            title: "Gold Hand #91",
            username: "@freezecorle...",
            account: "0x890aac...",
    
          },
          {
            id: 4,
            img: images[3],
            title: "Old Gold #874",
            username: "@0x3cr4c8...",
            account: "0x3cr4c8...",
          },
        
        {
          id: 9,
          img: images[8],
          title: "Cyber Wild Girls #44",
          username: "@0xg4l0fad...",
          account: "@0xg4l0fa...",
        },
        
          
      ],
  },
  {
    id: 5,
    title: "🛕 In Temple",
    content: [
        {
            id: 3,
            img: images[2],
            title: "Cyber Wild Man #745",
            username: "@0x4eh0t4...",
            account: "0x4eh0t4...",
          },
          {
            id: 4,
            img: images[3],
            title: "Old Gold #874",
            username: "@0x3cr4c8...",
            account: "0x3cr4c8...",
          },
          {
            id: 5,
            img: images[4],
            title: "Meraki Cyber #523",
            username: "@val2o543...",
            account: "0xh36f9n...",
          },
          {
            id: 6,
            img: images[5],
            title: "Cyber Robo #14",
            username: "@0xb0gfadr...",
            account: "0xb0gfadr...",
          },
        {
          id: 1,
          img: images[0],
          title: "Gold Hand #91",
          username: "@freezecorle...",
          account: "0x890aac...",
  
        },
        {
          id: 2,
          img: images[1],
          title: "Cyber Robo #2663",
          username: "@0x2bc08c...",
          account: "0x2bc08c...",
        },
        
        {
          id: 7,
          img: images[6],
          title: "Meraki Cyber #1463",
          username: "@0x4de6fr...",
          account: "0x4de6fr...",
        },
        {
          id: 8,
          img: images[7],
          title: "Spidey Cyber #874",
          username: "@spideycyber...",
          account: "@0xl9ka7c...",
        },
        {
          id: 9,
          img: images[8],
          title: "Cyber Wild Girls #44",
          username: "@0xg4l0fad...",
          account: "@0xg4l0fa...",
        },
      ],
  },
  {
    id: 6,
    title: "🌪️ In Void",
    content: [
       
        {
          id: 2,
          img: images[1],
          title: "Cyber Robo #2663",
          username: "@0x2bc08c...",
          account: "0x2bc08c...",
        },
        {
            id: 1,
            img: images[0],
            title: "Gold Hand #91",
            username: "@freezecorle...",
            account: "0x890aac...",
    
          },

        {
          id: 4,
          img: images[3],
          title: "Old Gold #874",
          username: "@0x3cr4c8...",
          account: "0x3cr4c8...",
        },
        {
            id: 3,
            img: images[2],
            title: "Cyber Wild Man #745",
            username: "@0x4eh0t4...",
            account: "0x4eh0t4...",
          },
          {
            id: 6,
            img: images[5],
            title: "Cyber Robo #14",
            username: "@0xb0gfadr...",
            account: "0xb0gfadr...",
          },
        {
          id: 5,
          img: images[4],
          title: "Meraki Cyber #523",
          username: "@val2o543...",
          account: "0xh36f9n...",
        },
        {
            id: 8,
            img: images[7],
            title: "Spidey Cyber #874",
            username: "@spideycyber...",
            account: "@0xl9ka7c...",
          },
        {
          id: 7,
          img: images[6],
          title: "Meraki Cyber #1463",
          username: "@0x4de6fr...",
          account: "0x4de6fr...",
        },

        {
          id: 9,
          img: images[8],
          title: "Cyber Wild Girls #44",
          username: "@0xg4l0fad...",
          account: "@0xg4l0fa...",
        },
      ],
  },
  {
    id: 7,
    title: "🦍 #BAYC",
    content:[
        {
            id: 5,
            img: images[4],
            title: "Meraki Cyber #523",
            username: "@val2o543...",
            account: "0xh36f9n...",
          },
          {
            id: 6,
            img: images[5],
            title: "Cyber Robo #14",
            username: "@0xb0gfadr...",
            account: "0xb0gfadr...",
          },
          {
            id: 7,
            img: images[6],
            title: "Meraki Cyber #1463",
            username: "@0x4de6fr...",
            account: "0x4de6fr...",
          },
          {
            id: 8,
            img: images[7],
            title: "Spidey Cyber #874",
            username: "@spideycyber...",
            account: "@0xl9ka7c...",
          },
          {
            id: 9,
            img: images[8],
            title: "Cyber Wild Girls #44",
            username: "@0xg4l0fad...",
            account: "@0xg4l0fa...",
          },
        {
          id: 1,
          img: images[0],
          title: "Gold Hand #91",
          username: "@freezecorle...",
          account: "0x890aac...",
  
        },
        {
          id: 2,
          img: images[1],
          title: "Cyber Robo #2663",
          username: "@0x2bc08c...",
          account: "0x2bc08c...",
        },
        {
          id: 3,
          img: images[2],
          title: "Cyber Wild Man #745",
          username: "@0x4eh0t4...",
          account: "0x4eh0t4...",
        },
        {
          id: 4,
          img: images[3],
          title: "Old Gold #874",
          username: "@0x3cr4c8...",
          account: "0x3cr4c8...",
        },
        
      ],
  },
];
